wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.2
    framework: xgboost
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.9
    start_time: 1662552683.637417
    t:
      1:
      - 5
      - 6
      - 53
      - 55
      2:
      - 5
      - 6
      - 53
      - 55
      3:
      - 23
      4: 3.8.9
      5: 0.13.2
      8:
      - 5
